In [3]:
import numpy as np
import pandas as pd

In [4]:

index = [['A',2010],['A',2020],['A',2025],['B',2010],['B',2020],['B',2025]]
population = [233,443,135,675,754,877]
i=pd.MultiIndex.from_tuples(index,names=['city','year'])
print(i)
pop = pd.Series(population,index=i)
print(pop)

MultiIndex([('A', 2010),
            ('A', 2020),
            ('A', 2025),
            ('B', 2010),
            ('B', 2020),
            ('B', 2025)],
           names=['city', 'year'])
city  year
A     2010    233
      2020    443
      2025    135
B     2010    675
      2020    754
      2025    877
dtype: int64

In [5]:
popu=pop.unstack()
print(popu)
pops=popu.stack()
print(pops)

year  2010  2020  2025
city
A      233   443   135
B      675   754   877
city  year
A     2010    233
      2020    443
      2025    135
B     2010    675
      2020    754
      2025    877
dtype: int64

In [6]:
index1 = [['A',2010],['A',2020],['A',2025],['B',2010],['B',2020],['B',2025]]
population1 = [233,443,135,675,754,877]
i1=pd.MultiIndex.from_arrays([['A','A','A','B','B','B'],[2010,2020,2025,2010,2020,2025]],names=['city','year'])
print(i1)
pop1 = pd.Series(population1,index=i1)
print(pop1)

MultiIndex([('A', 2010),
            ('A', 2020),
            ('A', 2025),
            ('B', 2010),
            ('B', 2020),
            ('B', 2025)],
           names=['city', 'year'])
city  year
A     2010    233
      2020    443
      2025    135
B     2010    675
      2020    754
      2025    877
dtype: int64

In [7]:
i2=pd.MultiIndex.from_product([['A','B'],[2010,2020,2025]],names=['city','year'])
pop2 = pd.Series(population1,index=i2)
print(pop2)

city  year
A     2010    233
      2020    443
      2025    135
B     2010    675
      2020    754
      2025    877
dtype: int64

In [8]:
i3 =pd.MultiIndex(levels=[['A','B'],[2010,2020,2025]],codes=[[0,0,0,1,1,1],[0,1,2,0,1,2]],names=['city','year'])
pop3 = pd.Series(population1,index=i3)
print(pop3)

city  year
A     2010    233
      2020    443
      2025    135
B     2010    675
      2020    754
      2025    877
dtype: int64

In [9]:
df=pd.DataFrame(np.random.rand(4,2),index=[['A','A','B','B'],[2010,2020,2010,2020]],columns=['data1','data2'])
print(df)

           data1     data2
A 2010  0.984882  0.858083
  2020  0.917652  0.348934
B 2010  0.914031  0.192506
  2020  0.351750  0.426796

In [10]:
print(pop['A',2010])

233

In [11]:
print(pop['A'])

year
2010    233
2020    443
2025    135
dtype: int64

In [12]:
print(pop[:,2010])

city
A    233
B    675
dtype: int64

In [13]:
print(pop[pop>300])

city  year
A     2020    443
B     2010    675
      2020    754
      2025    877
dtype: int64

update@15th,oct

In [16]:
pop.unstack(level=0)

city    A    B
year
2010  233  675
2020  443  754
2025  135  877

In [17]:
pop.unstack(level=1)

year  2010  2020  2025
city
A      233   443   135
B      675   754   877

In [18]:
pop.unstack().stack()

city  year
A     2010    233
      2020    443
      2025    135
B     2010    675
      2020    754
      2025    877
dtype: int64

In [19]:
pop_flat = pop.reset_index(name='population')
print(pop_flat)

  city  year  population
0    A  2010         233
1    A  2020         443
2    A  2025         135
3    B  2010         675
4    B  2020         754
5    B  2025         877

In [21]:
print(pop_flat.set_index(['city','year']))

           population
city year
A    2010         233
     2020         443
     2025         135
B    2010         675
     2020         754
     2025         877